apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: bestrong-memory-cpu-alert
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: BeStrongAlerts
    rules:
    - alert: MemoryUsageHigh
      expr: sum(container_memory_usage_bytes{container="bestrong-api-green"}) / sum(machine_memory_bytes) * 100 > 70
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage detected in BeStrong API"
        description: "Memory usage of BeStrong API pods is above 70%"
    - alert: CPUUsageHigh
      expr: sum(rate(container_cpu_usage_seconds_total{container="bestrong-api-green"}[1m])) / count(container_cpu_usage_seconds_total{container="bestrong-api-green"}) * 100 > 70
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected in BeStrong API"
        description: "CPU usage of BeStrong API pods is above 70%"