trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bestrong-helm-chart/*
    exclude:
      - '*'
variables:
  - group: lib-bestrong-k8s
  - name: containerRepository
    value: 'bestrongwebapp'
  - name: chartPath
    value: './bestrong-api-helm'
  - name: chartVersion
    value: '1.0.$(chartCounter)'
  - name: imageName
    value: 'crbestrongprodeastus001.azurecr.io/bestrongwebapp:v1'
  - name: chartACRName
    value: 'crbestrongakseastus001.azurecr.io'
  - name: chartName
    value: 'bestrong-api'
  - name: chartCounter
    value: $[counter(variables['appVersion'], 1)]

 

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerACRResgistry'
          command: 'login'
    
      - script:  docker pull $(imageName)
        workingDirectory: $(Build.SourcesDirectory)
        displayName: 'Docker Pull'
      - task: HelmInstaller@0
        inputs:
          helmVersion: '2.14.1'
          installKubectl: true

      - script: |
          helm lint $(chartPath)
        displayName: 'Lint Helm chart'
        continueOnError: true

      - script: |
          helm package --version $(chartVersion) $(chartPath)
        displayName: 'Package Helm chart'
      
      - script: |
          helm registry login $(chartACRName) --username $(ACR_USERNAME) --password $(ACR_PASSWORD)
        displayName: 'Login to Helm charts ACR'
      
      - script: |
          helm push $(chartName)-$(chartVersion).tgz oci://$(chartACRName)/helm
        displayName: 'Push helm chart to ACR'

      
      

- stage: Deploy
  condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: DeployHelmToAKS
    pool:
     vmImage: 'ubuntu-latest'
    steps:
      - task: HelmInstaller@0
        inputs:
          helmVersion: '2.14.1'
          installKubectl: true

      - script: |
          helm registry login $(chartACRName) --username $(ACR_USERNAME) --password $(ACR_PASSWORD)
        displayName: 'Login to Helm charts ACR'

      - script: |
          helm pull oci://$(chartACRName).azurecr.io/helm/$(chartName) --version $(chartVersion)
        displayName: 'Pull helm chart from ACR'

      - task: HelmDeploy@0
        displayName: 'Deploy latest chart to AKS'
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'Azure for Students(85bd95c0-eabe-403c-87b6-f72ae70ec867)'
          azureResourceGroup: 'rg-aks-eastus2'
          kubernetesCluster: 'myAKSCluster'
          namespace: 'ns-bestrong'
          command: 'upgrade'
          chartType: 'FilePath'
          chartPath: '$(Build.StagingDirectory)/$(chartPath)'
          chartVersion: '$(chartVersion)'
          releaseName: 'bestrong'
          arguments: '--create-namespace --install'
      

    
