trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bestrong-helm-chart/*
    exclude:
      - '*'
variables:
  - group: lib-bestrong-k8s
  - name: containerRepository
    value: 'bestrongwebapp'
  - name: chartPath
    value: './bestrong-api-helm'
  - name: chartVersion
    value: '1.0.$(chartCounter)'
  - name: imageName
    value: 'crbestrongprodeastus001.azurecr.io/bestrongwebapp:v1'
  - name: chartACRName
    value: 'crbestrongakseastus001.azurecr.io'
  - name: chartName
    value: 'bestrong-api'
  - name: chartCounter
    value: $[counter(variables['appVersion'], 1)]
  - name: colorImage
    value: 'green'

 

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: HelmInstaller@0
        inputs:
          helmVersion: '2.14.1'
          installKubectl: true

      - script: |
          helm lint $(chartPath)
        displayName: 'Lint Helm chart'
        continueOnError: true

      - script: |
          helm package --version $(chartVersion) $(chartPath)
        displayName: 'Package Helm chart'
      
      - script: |
          helm registry login $(chartACRName) --username $(ACR_USERNAME) --password $(ACR_PASSWORD)
        displayName: 'Login to Helm charts ACR'
      
      - script: |
          helm push $(chartName)-$(chartVersion).tgz oci://$(chartACRName)/helm
        displayName: 'Push helm chart to ACR'

      
- stage: Deploy
  condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: DeployHelmToAKS
    pool:
     vmImage: 'ubuntu-latest'
    steps:
      - task: HelmInstaller@0
        inputs:
          helmVersion: '2.14.1'
          installKubectl: true

      - script: |
          helm registry login $(chartACRName) --username $(ACR_USERNAME) --password $(ACR_PASSWORD)
        displayName: 'Login to Helm charts ACR'

      - script: |
          helm pull oci://$(chartACRName)/helm/$(chartName) --version $(chartVersion) -d $(Build.ArtifactStagingDirectory)
        displayName: 'Pull helm chart from ACR'
      
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'
      
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHelmACR'
          command: 'login'
    
      - task: HelmDeploy@0
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: 'BestrongAKS'
          namespace: 'default'
          command: 'upgrade'
          chartType: 'FilePath'
          chartPath: '$(Build.ArtifactStagingDirectory)/$(chartName)-$(chartVersion).tgz'
          chartVersion: '$(chartVersion)'
          releaseName: 'bestrong'
          overrideValues: '--set $(colorImage)Image.enabled=true --reuse-values --debug'
      
