trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bestrong-helm-chart/*
    exclude:
      - '*'

variables:
  - group: lib-bestrong-k8s
  - name: clusterName
    value: cluster_bestrong
  - name: resourceGroup
    value: rg-bestrong-aks
  - name: chartACRName
    value: 'crbestrongakseastus001.azurecr.io'
  - name: containerRepository
    value: 'bestrongwebapp'
  - name: chartPath
    value: './bestrong-api-helm'
  - name: chartVersion
    value: '1.0.$(chartCounter)'
  - name: chartName
    value: 'bestrong-api'
  - name: chartCounter
    value: $[counter(variables['appVersion'], 1)]

 

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: HelmInstaller@0
        inputs:
          helmVersion: '2.14.1'
          installKubectl: true

      - script: |
          helm lint $(chartPath)
        displayName: 'Lint Helm chart'
        continueOnError: true

      - script: |
          helm package --version $(chartVersion) $(chartPath)
        displayName: 'Package Helm chart'
      
      - script: |
          helm registry login $(chartACRName) --username $(ACR_USERNAME) --password $(ACR_PASSWORD)
        displayName: 'Login to Helm charts ACR'
      
      - script: |
          helm push $(chartName)-$(chartVersion).tgz oci://$(chartACRName)/helm
        displayName: 'Push helm chart to ACR'

      
- stage: Deploy
  condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: DeployHelmToAKS
    pool:
     vmImage: 'ubuntu-latest'
    steps:
      - task: HelmInstaller@0
        inputs:
          helmVersion: '2.14.1'
          installKubectl: true

      - script: |
          helm registry login $(chartACRName) --username $(ACR_USERNAME) --password $(ACR_PASSWORD)
        displayName: 'Login to Helm charts ACR'

      - script: |
          helm pull oci://$(chartACRName)/helm/$(chartName) --version $(chartVersion) -d $(Build.ArtifactStagingDirectory)
        displayName: 'Pull helm chart from ACR'
      
      - task: AzureCLI@2
        displayName: Login to AKS
        inputs:
          azureSubscription: 'Azure for Students(85bd95c0-eabe-403c-87b6-f72ae70ec867)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az aks get-credentials -n $(clusterName) -g $(resourceGroup) -a'
    

      - task: AzureCLI@2
        displayName: Change deployment color
        inputs:
          azureSubscription: 'Azure for Students(85bd95c0-eabe-403c-87b6-f72ae70ec867)'
          scriptType: 'bash'
          scriptLocation: 'scriptPath'
          scriptPath: 'test.sh'
          workingDirectory: '$(Build.SourcesDirectory)'
      - task: HelmDeploy@0
        inputs:
          connectionType: 'Azure Resource Manager'
          azureSubscription: 'Azure for Students(85bd95c0-eabe-403c-87b6-f72ae70ec867)'
          azureResourceGroup: 'rg-bestrong-aks'
          kubernetesCluster: 'cluster_bestrong'
          namespace: 'default'
          command: 'upgrade'
          chartType: 'FilePath'
          chartPath: '$(Build.ArtifactStagingDirectory)/$(chartName)-$(chartVersion).tgz'
          chartVersion: '$(chartVersion)'
          releaseName: 'bestrong'
          overrideValues: '--set $(color)Image.enabled=true --debug'

      
