{{ if .Values.blueImage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-blue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name}}
      slot: blue
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        slot: blue
    spec:
      containers:
      - name: {{ .Values.app.name }}-blue
        image: {{ .Values.image.repository }}:{{ .Values.blueImage.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
      #   volumeMounts:
      #     - name: tls
      #       mountPath: /etc/tls
      #       readOnly: true
        env:
        - name: color
          value: "blue"
      #     - name: TLS_CERT
      #       value: /etc/tls/tls.crt
      #     - name: TLS_KEY
      #       value: /etc/tls/tls.key
      # volumes:
      #   - name: tls
      #     secret:
      #       secretName: www-tls
{{ end }}