apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-api
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-api
    spec:
      containers:
      - name: bestrong-api
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
