{{ if .Values.greenImage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-green
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
      slot: green
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        slot: green
    spec:
      containers:
      - name: {{.Values.app.name}}-green
        image: {{ .Values.image.repository }}:{{ .Values.greenImage.tag}}
        ports:
        - containerPort: 80
        volumeMounts:
          - name: tls
            mountPath: /etc/tls
            readOnly: true
        env:
          - name: TLS_CERT
            value: /etc/tls/tls.crt
          - name: TLS_KEY
            value: /etc/tls/tls.key
      volumes:
        - name: tls
          secret:
            secretName: www-tls
{{ end }}