apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-api-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}-api
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}